//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCM5_GrossWeight
    {
        public int aa_id { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public string AreaID { get; set; }
        public Nullable<System.DateTime> MeasureTime { get; set; }
        public Nullable<int> Permit_Delete_Flag { get; set; }
        public Nullable<double> GrossWeightB { get; set; }
        public Nullable<double> TareWeight { get; set; }
    }
}
