//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLF_BASE_DATA
    {
        public string GUID { get; set; }
        public string NAME { get; set; }
        public string TREATNO { get; set; }
        public string HEATID { get; set; }
        public string PREHEATID { get; set; }
        public string STEELGRADEINDEX { get; set; }
        public string STEELGRADE { get; set; }
        public string LADLENO { get; set; }
        public string HEADFURNACE { get; set; }
        public string ASSISTANT { get; set; }
        public string SECONDHAND { get; set; }
        public Nullable<System.DateTime> PRODUCTIONDATE { get; set; }
        public Nullable<short> LOCKED { get; set; }
        public string SHIFT { get; set; }
        public string TEAM { get; set; }
        public Nullable<int> NC_CONFIRM_FLAG { get; set; }
    }
}
