//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLF_HEAT_GEARS_ITEM
    {
        public string GUID { get; set; }
        public string NAME { get; set; }
        public string TREATNO { get; set; }
        public string HEATID { get; set; }
        public string GEARS1 { get; set; }
        public string TIME1 { get; set; }
        public string GEARS2 { get; set; }
        public string TIME2 { get; set; }
        public string GEARS3 { get; set; }
        public string TIME3 { get; set; }
        public string GEARS4 { get; set; }
        public string TIME4 { get; set; }
        public string TOTALTIME { get; set; }
        public string PRODUCTIONTIME { get; set; }
        public Nullable<int> HEATCOUNT { get; set; }
        public string HEAD { get; set; }
        public string TEAM { get; set; }
        public string STEELGRADE { get; set; }
    }
}
