//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLF_LADLE_WEIGHT
    {
        public string GUID { get; set; }
        public string NAME { get; set; }
        public Nullable<short> LFID { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<short> STATUS { get; set; }
        public string LADLENO { get; set; }
        public Nullable<System.DateTime> LOG_TIME { get; set; }
        public string HEATID { get; set; }
        public Nullable<decimal> GROSSWEIGHT { get; set; }
        public Nullable<decimal> TAREWEIGHT { get; set; }
        public Nullable<decimal> KZWEIGHT { get; set; }
        public Nullable<decimal> CCMGROSSWEIGHT { get; set; }
        public Nullable<decimal> CCMTAREWEIGHT { get; set; }
        public Nullable<decimal> CCMLASTTAREWEIGHT { get; set; }
        public string AREA { get; set; }
        public Nullable<decimal> CCMINPUTAREWEIGHT { get; set; }
        public Nullable<decimal> LFJYWEIGHT { get; set; }
    }
}
