//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLF_PROCESS_SATUS
    {
        public string GUID { get; set; }
        public string NAME { get; set; }
        public string TREATNO { get; set; }
        public string HEATID { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<System.DateTime> CHANGE_TIME { get; set; }
        public string C_TS { get; set; }
    }
}
