//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_ems
    {
        public int id { get; set; }
        public Nullable<double> tg_chanliang { get; set; }
        public Nullable<double> tg_shuihao { get; set; }
        public Nullable<double> tg_dianhao { get; set; }
        public Nullable<double> tg_jiaolumeiqi { get; set; }
        public Nullable<double> tg_zhuanlumeiqi { get; set; }
        public Nullable<double> tg_danqi { get; set; }
        public Nullable<double> tg_yangqi { get; set; }
        public Nullable<double> tg_yaqi { get; set; }
        public Nullable<double> tg_meiqihuishou { get; set; }
        public Nullable<double> bxg_chanliang { get; set; }
        public Nullable<double> bxg_shuihao { get; set; }
        public Nullable<double> bxg_dianhao { get; set; }
        public Nullable<double> bxg_jiaolumeiqi { get; set; }
        public Nullable<double> bxg_zhuanlumeiqi { get; set; }
        public Nullable<double> bxg_danqi { get; set; }
        public Nullable<double> bxg_yangqi { get; set; }
        public Nullable<double> bxg_yaqi { get; set; }
        public string logtime { get; set; }
        public Nullable<int> bxg_flag { get; set; }
        public Nullable<double> tg_zhengqiwaigong { get; set; }
        public Nullable<double> bxg_zhengqiwaigong { get; set; }
        public Nullable<double> dl_zhengqiwaigong { get; set; }
    }
}
