//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_ems_day
    {
        public int id { get; set; }
        public Nullable<int> xuhao { get; set; }
        public string name { get; set; }
        public string zhibiao_sc { get; set; }
        public string zhibiao_cw { get; set; }
        public Nullable<double> yongliang { get; set; }
        public Nullable<double> danjia { get; set; }
        public string logtime { get; set; }
    }
}
