//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MEASURE_T
    {
        public string MATCHID { get; set; }
        public string CARNO { get; set; }
        public string CARTYPE { get; set; }
        public string RFIDID { get; set; }
        public string ICID { get; set; }
        public string OPERATYPE { get; set; }
        public string PLANID { get; set; }
        public string TASKCODE { get; set; }
        public string MATERIALCODE { get; set; }
        public string MATERIALNAME { get; set; }
        public string MATERIALSPECCODE { get; set; }
        public string MATERIALSPEC { get; set; }
        public string SHIPCODE { get; set; }
        public string SHIP { get; set; }
        public string SOURCECODE { get; set; }
        public string SOURCENAME { get; set; }
        public Nullable<System.DateTime> SOURCETIME { get; set; }
        public string SOURCEPLACE { get; set; }
        public string TARGETCODE { get; set; }
        public string TARGETNAME { get; set; }
        public Nullable<System.DateTime> TARGETTIME { get; set; }
        public string TARGETPLACE { get; set; }
        public string BASKET { get; set; }
        public Nullable<decimal> PLANWEIGHT { get; set; }
        public Nullable<decimal> PLANMATERIALCOUNT { get; set; }
        public Nullable<decimal> MATERIALCOUNT { get; set; }
        public Nullable<decimal> PLANCARCOUNT { get; set; }
        public Nullable<decimal> GROSS { get; set; }
        public Nullable<System.DateTime> GROSSTIME { get; set; }
        public string GROSSWEIGHID { get; set; }
        public string GROSSWEIGH { get; set; }
        public string GROSSOPERACODE { get; set; }
        public string GROSSOPERANAME { get; set; }
        public Nullable<decimal> GROSSGROUPNO { get; set; }
        public Nullable<decimal> GROSSSERIAL { get; set; }
        public Nullable<decimal> GROSSSPEED { get; set; }
        public string GROSSLOGID { get; set; }
        public Nullable<decimal> TARE { get; set; }
        public Nullable<System.DateTime> TARETIME { get; set; }
        public string TAREWEIGHID { get; set; }
        public string TAREWEIGH { get; set; }
        public string TAREOPERACODE { get; set; }
        public string TAREOPERANAME { get; set; }
        public Nullable<decimal> TAREGROUPNO { get; set; }
        public Nullable<decimal> TARESERIAL { get; set; }
        public string TARELOGID { get; set; }
        public Nullable<decimal> TARESPEED { get; set; }
        public Nullable<decimal> DEDUCTION { get; set; }
        public Nullable<System.DateTime> DEDUCTIONTIME { get; set; }
        public string DEDUCTIONCODE { get; set; }
        public string DEDUCTIONNAME { get; set; }
        public string DEDUCTIONOPERACODE { get; set; }
        public string DEDUCTIONOPERANAME { get; set; }
        public Nullable<decimal> SUTTLE { get; set; }
        public Nullable<System.DateTime> SUTTLETIME { get; set; }
        public string SUTTLEWEIGHID { get; set; }
        public string SUTTLEWEIGH { get; set; }
        public string SUTTLEOPERACODE { get; set; }
        public string SUTTLEOPERANAME { get; set; }
        public string MATCHIDB { get; set; }
        public Nullable<decimal> SUTTLEB { get; set; }
        public Nullable<decimal> GROSSB { get; set; }
        public Nullable<System.DateTime> GROSSTIMEB { get; set; }
        public string GROSSWEIGHIDB { get; set; }
        public string GROSSWEIGHB { get; set; }
        public string GROSSOPERACODEB { get; set; }
        public string GROSSOPERANAMEB { get; set; }
        public Nullable<decimal> GROSSGROUPNOB { get; set; }
        public Nullable<decimal> GROSSSERIALB { get; set; }
        public Nullable<decimal> GROSSSPEEDB { get; set; }
        public string GROSSLOGIDB { get; set; }
        public Nullable<decimal> TAREB { get; set; }
        public Nullable<System.DateTime> TARETIMEB { get; set; }
        public string TAREWEIGHIDB { get; set; }
        public string TAREWEIGHB { get; set; }
        public string TAREOPERACODEB { get; set; }
        public string TAREOPERANAMEB { get; set; }
        public Nullable<decimal> TAREGROUPNOB { get; set; }
        public Nullable<decimal> TARESERIALB { get; set; }
        public string TARELOGIDB { get; set; }
        public Nullable<decimal> TARESPEEDB { get; set; }
        public string BATCHCODE { get; set; }
        public Nullable<decimal> BFLAG { get; set; }
        public Nullable<decimal> PRINTGROSSNUM { get; set; }
        public Nullable<decimal> PRINTSUTTLENUM { get; set; }
        public string USERMEMO { get; set; }
        public string SYSMEMO { get; set; }
        public Nullable<decimal> VALIDFLAG { get; set; }
        public Nullable<System.DateTime> VALIDFLAGTIME { get; set; }
        public string VALIDFLAGOPERANAME { get; set; }
        public Nullable<decimal> RECORDTYPE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> UPTIME { get; set; }
        public Nullable<System.DateTime> UPTIMESTAMP { get; set; }
        public string DECUTIONTYPEBAK { get; set; }
        public string MOTORCADENAME { get; set; }
        public string MOTORCADECODE { get; set; }
        public Nullable<decimal> DEDUCTIONTYPE { get; set; }
        public string MEMO1 { get; set; }
        public string MEMO2 { get; set; }
        public string MEMO3 { get; set; }
        public string MEMO4 { get; set; }
        public string MEMO5 { get; set; }
        public string MEMO6 { get; set; }
        public string MEMO7 { get; set; }
        public string MEMO8 { get; set; }
        public string MEMO9 { get; set; }
        public string MEMO10 { get; set; }
        public string MEMO11 { get; set; }
        public string MEMO12 { get; set; }
        public string MEMO13 { get; set; }
        public string MEMO14 { get; set; }
        public string MEMO15 { get; set; }
        public Nullable<decimal> DEDUCTION2 { get; set; }
        public decimal UPDATENCFLAG { get; set; }
        public Nullable<decimal> PRINTCOUNT { get; set; }
        public Nullable<System.DateTime> UPDATENCDATE { get; set; }
    }
}
