//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_mes : DbContext
    {
        public Entities_mes()
            : base("name=Entities_mes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TS_INSCRAP> TS_INSCRAP { get; set; }
        public virtual DbSet<CLF_BASE_DATA> CLF_BASE_DATA { get; set; }
        public virtual DbSet<CLF_HEAT_GEARS> CLF_HEAT_GEARS { get; set; }
        public virtual DbSet<CLF_PROCESS_SATUS> CLF_PROCESS_SATUS { get; set; }
        public virtual DbSet<CLF_HEAT_GEARS_ITEM> CLF_HEAT_GEARS_ITEM { get; set; }
        public virtual DbSet<CLF_LADLE_WEIGHT> CLF_LADLE_WEIGHT { get; set; }
    }
}
