//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace inputscrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_INSCRAP
    {
        public string LOGTIME { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> INWEIGHT { get; set; }
        public Nullable<decimal> HSWEIGHT { get; set; }
        public Nullable<decimal> ZCWEIGHT { get; set; }
        public Nullable<decimal> STWEIGHT { get; set; }
    }
}
