//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace layui
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCM_Weight_His
    {
        public int CCMID { get; set; }
        public Nullable<System.DateTime> MeasureTime { get; set; }
        public Nullable<double> LadleWeight { get; set; }
        public Nullable<double> TundishWeight { get; set; }
    }
}
