//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace layui
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCURRENTSHIFTINFO
    {
        public string GUID { get; set; }
        public string NAME { get; set; }
        public string L3INDEX { get; set; }
        public string SHIFTTYPE { get; set; }
        public Nullable<short> SHIFTID { get; set; }
        public Nullable<short> TEAMID { get; set; }
        public string UNITTYPEID { get; set; }
        public string UNITID { get; set; }
        public Nullable<short> CURRENTID { get; set; }
        public Nullable<System.DateTime> BEGINPROCESSTIME { get; set; }
        public Nullable<System.DateTime> ENDPROCESSTIME { get; set; }
        public string SHIFTWARNING { get; set; }
    }
}
