//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace layui
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCRAP_OUTPUT_LOG
    {
        public string GUID { get; set; }
        public string NAME { get; set; }
        public string NO { get; set; }
        public string MATERIALTYPE { get; set; }
        public string MATERIALID { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string REASON { get; set; }
        public string TARGET { get; set; }
        public string STOREAREAID { get; set; }
        public string OPERATOR { get; set; }
        public string SHIFT { get; set; }
        public string TEAM { get; set; }
        public string SCRAP_SLOT_ID { get; set; }
        public string CAR_ID { get; set; }
        public string CAR_TYPE { get; set; }
        public Nullable<decimal> NET_WEIGHT { get; set; }
        public Nullable<decimal> GROSS_WEIGHT { get; set; }
        public Nullable<decimal> TARE_WEIGHT { get; set; }
        public Nullable<int> IRON_FLAG { get; set; }
        public string HEATID { get; set; }
    }
}
