//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace layui
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_Qyxx
    {
        public int Qyxxid { get; set; }
        public string cph { get; set; }
        public string matname { get; set; }
        public string custname { get; set; }
        public string chedao { get; set; }
        public int state { get; set; }
        public Nullable<int> qyds { get; set; }
    }
}
