//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace layui
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_YCCX
    {
        public int SAMPLE_YCCX_ID { get; set; }
        public Nullable<double> SJSL { get; set; }
        public Nullable<System.DateTime> RIQI { get; set; }
        public string MATNAME { get; set; }
        public string CUSTNAME { get; set; }
        public string MATCODE { get; set; }
        public string CUSTCODE { get; set; }
        public string ITEMNAME { get; set; }
        public string ITEMCODE { get; set; }
        public string JYBZ { get; set; }
        public Nullable<double> CHECKVAL { get; set; }
        public Nullable<int> CHESHU { get; set; }
        public string ZYDANHAO { get; set; }
        public string leixing { get; set; }
        public string rq { get; set; }
    }
}
